### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by JanTvrdik**

### CODE REVIEW

**Comment by dg** [comment]
License file is on remote (production) server really useless.

**Comment by hrach** [comment]
just lol. github is also remote server, so i'm going to delete it. nette can lives without it on remote servers.

**Comment by dg** [comment]
Feel free to remove nette license on all your production servers.

**Comment by JanTvrdik** [comment]
The motivation for keeping license files is simple. I work on open-source projects with committed `vendor` directory ([example](https://github.com/fitak/fitak/tree/dev/vendor)). Removing licenses under this conditions is AFAIK not possible.

**Comment by hrach** [comment]
I wonder what was the purpose of this package at all. The only reason to use has been mentioned by Jan Tvrdik. Why should I remove this useless files on production servers? I really don't care. David, it's getting clear that you are not so experienced with using composer for the final products.

**Comment by JanTvrdik** [comment]
@hrach Keep calm and let me handle the discussion. Your insults are both stupid and annoying.

> Why should I remove this useless files on production servers?

You may want to remove them locally before deploying to production. In that case you may not need license files as pointed out by @dg.

**Comment by hrach** [comment]
@JanTvrdik you are not right, the code has to be distributed always with it's licence, not matter how broad the audience is. Eg. 

> The above copyright notice and this permission notice shall be included in
> all copies or substantial portions of the Software.

**Comment by hrach** [comment]
I would appreciate, if you both stop changing your posted comments without marking the changed parts.

**Comment by JanTvrdik** [comment]
> if you both stop changing your posted comments without marking the changed parts

Sorry, I do this all the time. Mostly to fix typos and add clarity to reduce confusion.

**Comment by dg** [comment]
@hrach please go away

@JanTvrdik I am not commiting vendor (yes, it's bad, I know) so I did not think about this usage. In this case it makes sense to keep the license.

**Comment by dg** [comment]
Thanx!

**Comment by dg** [comment]
@JanTvrdik sometimes is vendor structure deeper ([example](https://github.com/JanTvrdik/NetteDocumentationEditor/tree/master/vendor/zendframework/zend-escaper/Zend/Escaper)), do you know why?

**Comment by JanTvrdik** [comment]
@dg Because of `target-dir` ([doc](https://getcomposer.org/doc/04-schema.md#target-dir)). Yes, we should probably support that as well even though it is an deprecated option.

**Pull request merged**
